from django.db import models

# Create your models here.

class foodslistings(models.Model):
    #id = models.IntegerField()
    is_claimed = models.CharField(max_length=255, null=True)
    rating = models.CharField(max_length=255, null=True)
    mobile_url = models.CharField(max_length=255, null=True)
    rating_image_url = models.CharField(max_length=255, null=True)
    review_count = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255, null=True)
    rating_image_url_small = models.CharField(max_length=255, null=True)
    url = models.CharField(max_length=255, null=True)
    is_closed = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=255, null=True)
    snippet_text = models.CharField(max_length=255, null=True)
    image_url = models.CharField(max_length=255, null=True)
    categories = models.CharField(max_length=255, null=True)
    display_phone = models.CharField(max_length=255, null=True)
    rating_image_url_large = models.CharField(max_length=255, null=True)
    identifier = models.CharField(max_length=255, null=True)
    snippet_image_url = models.CharField(max_length=255, null=True)
    location = models.CharField(max_length=255, null=True)
    deals = models.CharField(max_length=255, null=True)
    #display_address = models.CharField(max_length=255)
    #neighborhoods = models.CharField(max_length=255)
    #postal_code = models.CharField(max_length=255)
    #country_code = models.CharField(max_length=255)
    #address = models.CharField(max_length=255)
    #state_code = models.CharField(max_length=255)

class artslistings(models.Model):
    #id = models.IntegerField()
    is_claimed = models.CharField(max_length=255, null=True)
    rating = models.CharField(max_length=255, null=True)
    mobile_url = models.CharField(max_length=255, null=True)
    rating_image_url = models.CharField(max_length=255, null=True)
    review_count = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255, null=True)
    rating_image_url_small = models.CharField(max_length=255, null=True)
    url = models.CharField(max_length=255, null=True)
    is_closed = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=255, null=True)
    snippet_text = models.CharField(max_length=255, null=True)
    image_url = models.CharField(max_length=255, null=True)
    categories = models.CharField(max_length=255, null=True)
    display_phone = models.CharField(max_length=255, null=True)
    rating_image_url_large = models.CharField(max_length=255, null=True)
    identifier = models.CharField(max_length=255, null=True)
    snippet_image_url = models.CharField(max_length=255, null=True)
    location = models.CharField(max_length=255, null=True)
    deals = models.CharField(max_length=255, null=True)

    #display_address = models.CharField(max_length=255)
    #neighborhoods = models.CharField(max_length=255)
    #postal_code = models.CharField(max_length=255)
    #country_code = models.CharField(max_length=255)
    #address = models.CharField(max_length=255)
    #state_code = models.CharField(max_length=255)

class shopslistings(models.Model):
    #id = models.IntegerField()
    is_claimed = models.CharField(max_length=255, null=True)
    rating = models.CharField(max_length=255, null=True)
    mobile_url = models.CharField(max_length=255, null=True)
    rating_image_url = models.CharField(max_length=255, null=True)
    review_count = models.CharField(max_length=255, null=True)
    rating_image_url_small = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255, null=True)
    url = models.CharField(max_length=255, null=True)
    is_closed = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=255, null=True)
    snippet_text = models.CharField(max_length=255, null=True)
    image_url = models.CharField(max_length=255, null=True)
    categories = models.CharField(max_length=255, null=True)
    display_phone = models.CharField(max_length=255, null=True)
    rating_image_url_large = models.CharField(max_length=255, null=True)
    identifier = models.CharField(max_length=255, null=True)
    snippet_image_url = models.CharField(max_length=255, null=True)
    location = models.CharField(max_length=255, null=True)
    menu_provider = models.CharField(max_length=255, null=True)
    menu_date_updated = models.CharField(max_length=255, null=True)

    #display_address = models.CharField(max_length=255)
    #neighborhoods = models.CharField(max_length=255)
    #postal_code = models.CharField(max_length=255)
    #country_code = models.CharField(max_length=255)
    #address = models.CharField(max_length=255)
    #state_code = models.CharField(max_length=255)